#!/bin/sh

######
# Test the donaimatch binary; the optional $1 is the executable donaimatch
###

if [ "$#" -ge 1 ]
then
	donaimatch="$1"
else
	donaimatch="$(dirname $0)/../donaimatch"
fi

_haserr=0

# Print error for an erroneously accepted string.
# $1 - the tested selector
# $2 - the tested donai
perr_accept() {
	_haserr=1
	echo ERROR \""$1"\" accepts \""$2"\"
}

# Print error for an erroneously unaccepted string.
# $1 - the tested selector
# $2 - the tested donai
perr_notaccept() {
	_haserr=1
	echo ERROR \""$1"\" does not accept \""$2"\"
}


######
# First test a bunch of mismatches
###

# DoNAI subject
s="\(user\)@example.net"

t="e.net"
"$donaimatch" -q "$t" "$s" && perr_accept "$t" "$s"

t=".com"
"$donaimatch" -q "$t" "$s" && perr_accept "$t" "$s"

t="@.com"
"$donaimatch" -q "$t" "$s" && perr_accept "$t" "$s"

t=".f"
"$donaimatch" -q "$t" "$s" && perr_accept "$t" "$s"

t=".fo"
"$donaimatch" -q "$t" "$s" && perr_accept "$t" "$s"

t="@n"
"$donaimatch" -q "$t" "$s" && perr_accept "$t" "$s"

t="@ne"
"$donaimatch" -q "$t" "$s" && perr_accept "$t" "$s"


######
# Now test some matches
###

# DoNAI subject
s="\(user\)@example.net"

t="."
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="net"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t=".net"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="@."
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="@.net"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="\(user\)@."
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"


######
# Tests from http://donai.arpa2.net/selector.html
###

# DoNAI subject
s="example.org"

t="."
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t=".org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="example.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

# DoNAI subject
s="example.org"
t=".org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

# DoNAI subject
s="example.org"
t=".example.org"
"$donaimatch" -q "$t" "$s" && perr_accept "$t" "$s"

t="example.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

# DoNAI subject
s="@example.org"

t="@example.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="@.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="@."
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

# DoNAI subject
s="john@example.org"

t="john@example.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="@example.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="john@.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="@.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="john@."
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="@."
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"


######
# Tests from http://donai.arpa2.net/selector.html considering sub-names.
###

# DoNAI subject
s="sales+john@example.org"

t="sales+john@example.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="sales+@example.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="sales@example.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="@example.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="sales+john@.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="sales+@.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="sales@.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="@.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="sales+john@."
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="sales+@."
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="sales@."
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="@."
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

# DoNAI subject
s="john+singer@example.org"

t="john+singer@example.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="@example.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="john+singer@.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="@.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="john+singer@."
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="@."
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

# DoNAI subject
s="john@example.org"

t="john@example.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="john+@example.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="@example.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="john@.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="john+@.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="@.org"
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="john@."
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="john+@."
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"

t="@."
"$donaimatch" -q "$t" "$s" || perr_notaccept "$t" "$s"


###
# Finish up

if [ "$_haserr" -ne 0 ]; then
	# assume errors are already printed
	exit 1
fi
